// screens/InvoiceScreen.js
import React from "react";
import {
  View,
  Text,
  FlatList,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  Alert,
} from "react-native";
import { Ionicons, MaterialIcons } from "@expo/vector-icons";
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";

const InvoiceScreen = ({ route, navigation }) => {
  const { invoiceData } = route.params || {};

  if (!invoiceData) {
    return (
      <View style={styles.loaderContainer}>
        <Text style={{ color: "red", fontSize: 16 }}>
          Invoice data not available.
        </Text>
      </View>
    );
  }

  const {
    invoice_no,
    employee_name,
    payment_mode,
    patient_name,
    patient_age,
    patient_phone,
    medicines,
    total_amount,
  } = invoiceData;

  const currentDate = new Date();
  const istOffset = 5.5 * 60;
  const istTime = new Date(currentDate.getTime() + istOffset * 60000);
  const formattedDate = istTime.toLocaleDateString("en-IN");
  const formattedTime = istTime.toLocaleTimeString("en-IN");

  const generatePDF = async () => {
    const htmlContent = `...`; // same as before
    try {
      const { uri } = await Print.printToFileAsync({ html: htmlContent });
      await Sharing.shareAsync(uri);
    } catch (error) {
      Alert.alert("Error", "Failed to generate PDF.");
      console.error("PDF Error:", error);
    }
  };

  return (
    <View style={styles.container}>
      {/* Header */}
      <View style={styles.header}>
        <TouchableOpacity onPress={() => navigation.goBack()}>
          <Ionicons name="arrow-back" size={26} color="#fff" />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Invoice</Text>
        <View style={{ width: 26 }} />
      </View>

      <ScrollView contentContainerStyle={styles.content}>
        {/* Hospital Name */}
        <Text style={styles.hospitalName}>
          <MaterialIcons name="local-hospital" size={28} color="#fff" /> Bharat Medical Hall
        </Text>

        {/* Invoice Info */}
        <View style={[styles.card, { borderLeftColor: "#FFD6D6" }]}>
          <View style={styles.cardHeader}>
            <Ionicons name="document-text-outline" size={22} color="#FF6B6B" />
            <Text style={[styles.cardTitle, { color: "#FF6B6B" }]}>Invoice Details</Text>
          </View>
          <Text style={styles.text}>Invoice No: {invoice_no}</Text>
          <Text style={styles.text}>Date & Time: {formattedDate} {formattedTime}</Text>
          <Text style={styles.text}>Generated By: {employee_name}</Text>
          <Text style={styles.text}>Payment Mode: {payment_mode}</Text>
        </View>

        {/* Patient Info */}
        <View style={[styles.card, { borderLeftColor: "#C6D8FF" }]}>
          <View style={styles.cardHeader}>
            <Ionicons name="person-outline" size={22} color="#4D79FF" />
            <Text style={[styles.cardTitle, { color: "#4D79FF" }]}>Patient Details</Text>
          </View>
          <Text style={styles.text}>Name: {patient_name}</Text>
          <Text style={styles.text}>Age: {patient_age}</Text>
          <Text style={styles.text}>Phone: {patient_phone}</Text>
        </View>

        {/* Medicines / Items */}
        <View style={[styles.card, { borderLeftColor: "#B2FFD6" }]}>
          <View style={styles.cardHeader}>
            <Ionicons name="medkit-outline" size={22} color="#34D399" />
            <Text style={[styles.cardTitle, { color: "#34D399" }]}>Medicines / Items</Text>
          </View>
          {medicines?.length > 0 ? (
            <FlatList
              data={medicines}
              keyExtractor={(item, index) => index.toString()}
              renderItem={({ item }) => (
                <View style={styles.medicineRow}>
                  <Text style={styles.medicineText}>{item.name}</Text>
                  <Text style={styles.medicineText}>Qty: {item.quantity}</Text>
                  <Text style={styles.medicineText}>₹{item.total}</Text>
                </View>
              )}
              scrollEnabled={false}
            />
          ) : (
            <Text style={styles.text}>No items added.</Text>
          )}
        </View>

        {/* Total */}
       <View style={styles.totalContainer}>
  <View style={styles.totalRow}>
    <Ionicons name="cash-outline" size={22} color="#000" style={{ marginRight: 8 }} />
    <Text style={styles.totalText}>Grand Total: ₹{parseFloat(total_amount).toFixed(2)}</Text>
  </View>
</View>

        {/* PDF Button */}
        <TouchableOpacity style={styles.pdfButton} onPress={generatePDF}>
          <Ionicons name="document-text" size={20} color="#fff" />
          <Text style={styles.pdfButtonText}>Download PDF</Text>
        </TouchableOpacity>
      </ScrollView>
    </View>
  );
};

export default InvoiceScreen;

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F9FAFB" , marginTop:20},
  loaderContainer: { flex: 1, justifyContent: "center", alignItems: "center" },
  header: {
    flexDirection: "row",
    alignItems: "center",
    padding: 15,
    backgroundColor: "#4D79FF",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 5,
  },
  headerTitle: { flex: 1, textAlign: "center", fontSize: 20, fontWeight: "bold", color: "#fff" },
  hospitalName: {
    fontSize: 24,
    fontWeight: "bold",
    textAlign: "center",
    marginVertical: 12,
    color: "#4D79FF",
    backgroundColor: "#E0E8FF",
    paddingVertical: 8,
    borderRadius: 12,
  },
  content: { paddingHorizontal: 15, paddingBottom: 30 },
  card: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 15,
    marginBottom: 15,
    borderLeftWidth: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  cardHeader: { flexDirection: "row", alignItems: "center", marginBottom: 10 },
  cardTitle: { fontSize: 16, fontWeight: "bold", marginLeft: 8 },
  text: { fontSize: 14, marginBottom: 4, color: "#4B5563" },
  medicineRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 6,
    borderBottomWidth: 0.5,
    borderBottomColor: "#E5E7EB",
  },
  medicineText: { fontSize: 14, color: "#374151", flex: 1, textAlign: "center" },
totalContainer: {
  padding: 14,
  borderRadius: 12,
  marginTop: 10,
},
totalRow: {
  flexDirection: "row",
  justifyContent: "center",
  alignItems: "center",
},
totalText: { 
  fontSize: 18, 
  fontWeight: "bold", 
  textAlign: "center", 
  color: "#111111" // black text
},


  pdfButton: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#10B981",
    padding: 14,
    borderRadius: 12,
    marginTop: 20,
    shadowColor: "#10B981",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  pdfButtonText: { color: "#fff", fontSize: 16, fontWeight: "bold", marginLeft: 8 },
});
