import React from "react";
import {
  View,
  Text,
  FlatList,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  Alert,
  Platform,
  useWindowDimensions,
  StatusBar
} from "react-native";
import { Ionicons, MaterialIcons } from "@expo/vector-icons";
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";

const InvoiceScreen = ({ route, navigation }) => {
  const { invoiceData } = route.params || {};
  const { width: SCREEN_WIDTH } = useWindowDimensions();
  const isDesktop = SCREEN_WIDTH > 800;

  if (!invoiceData) {
    return (
      <View style={styles.loaderContainer}>
        <Text style={{ color: "red", fontSize: 16 }}>Invoice data not available.</Text>
      </View>
    );
  }

  const {
    invoice_no,
    employee_name,
    payment_mode,
    patient_name,
    patient_age,
    patient_phone,
    medicines,
    total_amount,
  } = invoiceData;

  const currentDate = new Date();
  const istOffset = 5.5 * 60;
  const istTime = new Date(currentDate.getTime() + istOffset * 60000);
  const formattedDate = istTime.toLocaleDateString("en-IN");
  const formattedTime = istTime.toLocaleTimeString("en-IN");

  const showAlert = (title, message) => {
    if (Platform.OS === "web") window.alert(`${title}\n\n${message}`);
    else Alert.alert(title, message);
  };

  const generatePDF = async () => {
    if (!invoiceData) return showAlert("Error", "No invoice data found");

    const htmlContent = `
      <html>
        <head>
          <style>
            body { font-family: 'Helvetica', sans-serif; padding: 40px; color: #333; }
            .header { border-bottom: 2px solid #0D6EFD; padding-bottom: 20px; margin-bottom: 30px; }
            h1 { color: #0D6EFD; margin: 0; }
            .info-table { width: 100%; margin-bottom: 30px; }
            .med-table { width: 100%; border-collapse: collapse; }
            .med-table th { background: #F8F9FA; padding: 12px; text-align: left; border-bottom: 2px solid #DEE2E6; }
            .med-table td { padding: 12px; border-bottom: 1px solid #EEE; }
            .total-row { font-size: 20px; font-weight: bold; text-align: right; margin-top: 30px; padding-top: 20px; border-top: 2px solid #0D6EFD; }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>Bharat Medical Hall</h1>
            <p>Invoice No: ${invoice_no} | Date: ${formattedDate}</p>
          </div>
          <table class="info-table">
            <tr>
              <td><strong>Patient:</strong> ${patient_name} (${patient_age} Yrs)</td>
              <td align="right"><strong>Generated By:</strong> ${employee_name}</td>
            </tr>
            <tr>
              <td><strong>Phone:</strong> ${patient_phone}</td>
              <td align="right"><strong>Payment:</strong> ${payment_mode}</td>
            </tr>
          </table>
          <table class="med-table">
            <thead>
              <tr><th>Item Name</th><th>Qty</th><th align="right">Amount</th></tr>
            </thead>
            <tbody>
              ${medicines?.map(med => `<tr><td>${med.name}</td><td>${med.quantity}</td><td align="right">₹${med.total}</td></tr>`).join("")}
            </tbody>
          </table>
          <div class="total-row">Grand Total: ₹${parseFloat(total_amount).toFixed(2)}</div>
        </body>
      </html>
    `;

    try {
      if (Platform.OS === "web") {
        const printWindow = window.open("", "_blank");
        printWindow.document.write(htmlContent);
        printWindow.document.close();
        printWindow.print();
      } else {
        const { uri } = await Print.printToFileAsync({ html: htmlContent });
        await Sharing.shareAsync(uri);
      }
    } catch (error) {
      showAlert("Error", "Failed to generate PDF.");
    }
  };

  return (
    <View style={styles.container}>
      <StatusBar barStyle="dark-content" backgroundColor="#fff" />
      <View style={[styles.mainWrapper, { flexDirection: isDesktop ? 'row' : 'column' }]}>
        
        {/* LEFT BRANDING SIDE */}
        {isDesktop && (
          <View style={styles.brandingSide}>
            <View style={styles.brandOverlay}>
              <View style={styles.successIconBox}>
                <Ionicons name="checkmark-circle" size={50} color="#fff" />
              </View>
              <Text style={styles.heroTitle}>Invoice Generated!</Text>
              <Text style={styles.heroSubtitle}>Transaction recorded successfully</Text>
              <View style={styles.dividerLight} />
              <Text style={styles.heroDescription}>
                The billing details have been encrypted and saved to the central database. You can now download the PDF or print a hard copy for the patient.
              </Text>
              
              <TouchableOpacity style={styles.actionBtnOutline} onPress={() => navigation.navigate("AdminDashboard")}>
                <Text style={styles.actionBtnOutlineText}>Back to Dashboard</Text>
              </TouchableOpacity>
            </View>
          </View>
        )}

        {/* RIGHT INVOICE CONTENT */}
        <View style={[styles.invoiceSide, { width: isDesktop ? '60%' : '100%' }]}>
          <ScrollView contentContainerStyle={styles.scrollContent} showsVerticalScrollIndicator={false}>
            {!isDesktop && (
              <TouchableOpacity onPress={() => navigation.navigate("Dashboard")} style={styles.mobileBack}>
                <Ionicons name="arrow-back" size={24} color="#0D6EFD" />
              </TouchableOpacity>
            )}

            <View style={styles.invoicePaper}>
              {/* Top Header */}
              <View style={styles.invoiceHeader}>
                <View>
                  <Text style={styles.brandLabel}>INVOICE</Text>
                  <Text style={styles.invoiceNum}>#{invoice_no}</Text>
                </View>
                <View style={styles.dateBox}>
                  <Text style={styles.dateLabel}>{formattedDate}</Text>
                  <Text style={styles.timeLabel}>{formattedTime}</Text>
                </View>
              </View>

              <View style={styles.sectionDivider} />

              {/* Billing Info Grid */}
              <View style={styles.infoGrid}>
                <View style={styles.infoBlock}>
                  <Text style={styles.smallLabel}>PATIENT DETAILS</Text>
                  <Text style={styles.infoValue}>{patient_name}</Text>
                  <Text style={styles.infoSubText}>{patient_age} Yrs • {patient_phone}</Text>
                </View>
                <View style={styles.infoBlock}>
                  <Text style={styles.smallLabel}>PAYMENT MODE</Text>
                  <View style={styles.badge}>
                    <Text style={styles.badgeText}>{payment_mode.toUpperCase()}</Text>
                  </View>
                </View>
              </View>

              {/* Medicines Table */}
              <View style={styles.tableHeader}>
                <Text style={[styles.tableHeadText, { flex: 2 }]}>ITEM DESCRIPTION</Text>
                <Text style={[styles.tableHeadText, { flex: 0.5, textAlign: 'center' }]}>QTY</Text>
                <Text style={[styles.tableHeadText, { flex: 1, textAlign: 'right' }]}>TOTAL</Text>
              </View>

              {medicines?.map((item, index) => (
                <View key={index} style={styles.tableRow}>
                  <Text style={[styles.rowText, { flex: 2, fontWeight: '600' }]}>{item.name}</Text>
                  <Text style={[styles.rowText, { flex: 0.5, textAlign: 'center' }]}>{item.quantity}</Text>
                  <Text style={[styles.rowText, { flex: 1, textAlign: 'right', color: '#000' }]}>₹{item.total}</Text>
                </View>
              ))}

              <View style={styles.grandTotalContainer}>
                <Text style={styles.totalLabel}>Grand Total</Text>
                <Text style={styles.totalValue}>₹{parseFloat(total_amount).toFixed(2)}</Text>
              </View>

              <View style={styles.footerInfo}>
                <Text style={styles.footerText}>Billed by: {employee_name}</Text>
                <Text style={styles.footerText}>Bharat Medical Hall • All rights reserved</Text>
              </View>
            </View>

            <TouchableOpacity style={styles.printBtn} onPress={generatePDF}>
              <Ionicons name="print" size={20} color="#fff" />
              <Text style={styles.printBtnText}>DOWNLOAD / PRINT INVOICE</Text>
            </TouchableOpacity>
          </ScrollView>
        </View>
      </View>
    </View>
  );
};

export default InvoiceScreen;

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F8F9FA" },
  mainWrapper: { flex: 1 },
  loaderContainer: { flex: 1, justifyContent: "center", alignItems: "center" },

  // Left Side (Branding)
  brandingSide: { flex: 1, backgroundColor: '#0D6EFD', padding: 40, justifyContent: 'center' },
  brandOverlay: { maxWidth: 400, alignSelf: 'center' },
  successIconBox: { width: 80, height: 80, backgroundColor: 'rgba(255,255,255,0.2)', borderRadius: 25, justifyContent: 'center', alignItems: 'center', marginBottom: 20 },
  heroTitle: { fontSize: 32, fontWeight: '800', color: '#fff' },
  heroSubtitle: { fontSize: 18, color: 'rgba(255,255,255,0.8)', marginTop: 5 },
  dividerLight: { height: 1, backgroundColor: 'rgba(255,255,255,0.2)', marginVertical: 25 },
  heroDescription: { fontSize: 15, color: 'rgba(255,255,255,0.7)', lineHeight: 24, marginBottom: 40 },
  actionBtnOutline: { borderWidth: 1, borderColor: '#fff', paddingVertical: 12, borderRadius: 10, alignItems: 'center', width: 200 },
  actionBtnOutlineText: { color: '#fff', fontWeight: '700' },

  // Right Side (Invoice Paper)
  invoiceSide: { flex: 1, backgroundColor: '#F8F9FA' },
  scrollContent: { paddingHorizontal: '8%', paddingVertical: 40 },
  mobileBack: { marginBottom: 20 },
  invoicePaper: { 
    backgroundColor: '#fff', borderRadius: 20, padding: 35, 
    shadowColor: '#000', shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.05, shadowRadius: 15, elevation: 5 
  },
  invoiceHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  brandLabel: { fontSize: 12, fontWeight: '800', color: '#0D6EFD', letterSpacing: 2 },
  invoiceNum: { fontSize: 24, fontWeight: '900', color: '#1A1A1A', marginTop: 4 },
  dateBox: { alignItems: 'right' },
  dateLabel: { fontSize: 15, fontWeight: '700', color: '#1A1A1A' },
  timeLabel: { fontSize: 13, color: '#6c757d' },
  sectionDivider: { height: 1, backgroundColor: '#F1F3F5', marginVertical: 25 },
  infoGrid: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 30 },
  smallLabel: { fontSize: 11, fontWeight: '800', color: '#adb5bd', marginBottom: 8 },
  infoValue: { fontSize: 16, fontWeight: '700', color: '#1A1A1A' },
  infoSubText: { fontSize: 13, color: '#6c757d', marginTop: 2 },
  badge: { backgroundColor: '#E7F1FF', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 6, alignSelf: 'flex-start' },
  badgeText: { fontSize: 11, fontWeight: '800', color: '#0D6EFD' },

  tableHeader: { flexDirection: 'row', paddingBottom: 12, borderBottomWidth: 2, borderBottomColor: '#F1F3F5' },
  tableHeadText: { fontSize: 11, fontWeight: '800', color: '#adb5bd' },
  tableRow: { flexDirection: 'row', paddingVertical: 15, borderBottomWidth: 1, borderBottomColor: '#F8F9FA' },
  rowText: { fontSize: 14, color: '#495057' },

  grandTotalContainer: { 
    flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', 
    marginTop: 30, padding: 20, backgroundColor: '#F8F9FA', borderRadius: 15 
  },
  totalLabel: { fontSize: 16, fontWeight: '700', color: '#495057' },
  totalValue: { fontSize: 26, fontWeight: '900', color: '#0D6EFD' },
  
  footerInfo: { marginTop: 40, alignItems: 'center' },
  footerText: { fontSize: 12, color: '#adb5bd', marginBottom: 4 },

  printBtn: { 
    height: 60, backgroundColor: '#0D6EFD', borderRadius: 30, 
    flexDirection: 'row', justifyContent: 'center', alignItems: 'center', marginTop: 30,
    shadowColor: '#0D6EFD', shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.3, shadowRadius: 10, elevation: 8
  },
  printBtnText: { color: "#fff", fontSize: 15, fontWeight: "800", marginLeft: 10 },
});